FROM python:3.12-slim

WORKDIR /app

COPY python/requirements.txt .

RUN apt-get update && apt-get install -y gcc libpq-dev

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt --verbose

COPY python/ .

EXPOSE 5000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
